### ISSUE TITLE
AP small, medium, and large

### ISSUE THREAD

**Issue by ChristophReich1996** [YihongSun/MOD-UV#1]
Hi @YihongSun,

I was wondering if you could share which object size you have utilized to validate on KITTI. More specifically, what are the areas of AP_S, AP_M, and AP_L? Have you followed the official KITTI areas or the COCO sizes? Additionally, on which resolution was the validation on KITTI performed? Thanks for the help!

Cheers,
Christoph

**Comment by YihongSun** [comment]
Hello,

Thank you for your interest in our work!

For evaluation on KITTI, we took the detector trained on Waymo and directly applied to the 2D Detection training set for KITTI. We did not change the image resolution for evaluation, but for consistency with evaluation on other datasets, we used the [area metrics defined by COCO](https://cocodataset.org/#detection-eval).

Hope this helps!

**Comment by ChristophReich1996** [comment]
Yes, this helps a lot, thanks! PS: Very nice work!
